### ISSUE TITLE
Not Found (HTTP status code: 404, URL: https://github.com/google/mediapipe/raw/master/mediapipe/modules/hand_landmark/hand_landmark.tflite)

### ISSUE THREAD

**Issue by minhaaz52** [supremetech/mediapipe-demo-hand-detection#2]
While I'm creating app, I'm getting this error. Kindly help please.

**Comment by st-duymai** [comment]
Hey @minhaaz52
Look like the hand_landmark tflite file is unavailable. So I update the new url at this pr: #3 .
Please check it and tell me if it has any problem. Thanks

**Comment by minhaaz52** [comment]
Thank you so much, sir.
It worked.
Sir, I just have one question. Is this model the same as mediapipe hand model?
Means, this will give same landmarks points as mediapipe hand model gives (all 21  landmark points)?

**Comment by duy-maimanh** [comment]
@minhaaz52 
Yes, it same as mediapipe hand model.

**Comment by minhaaz52** [comment]
Ok sir.
Thank u so much sir.
